services:
  cache-warmer:
    build: .
    container_name: cache-warmer
    restart: always
    env_file:
      - .env
    volumes:
      - ./logs:/root/cache-warmer/logs

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx.conf.template:/etc/nginx/templates/nginx.conf.template:ro
      - /etc/letsencrypt:/etc/letsencrypt:ro
    entrypoint: >
      sh -c "
        envsubst '$$DOMAIN $$SSL_CERT_PATH $$SSL_CERT_KEY_PATH' < /etc/nginx/templates/nginx.conf.template > /etc/nginx/nginx.conf &&
        nginx -g 'daemon off;'"