services:
  cache-warmer:
    build: .
    container_name: cache-warmer
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/root/cache-warmer/logs

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "443:443"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro