services:
  cache-warmer:
    build: .
    container_name: cache-warmer
    restart: always
    env_file:
      - .env
    ports:
      - "3000:3000"
    volumes:
      - ./logs:/root/cache-warmer/logs

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx:/etc/nginx/templates
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: >
      sh -c "
        if [ -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]; then
          echo '✅ HTTPS certificate found, starting in HTTPS mode' &&
          envsubst '$$DOMAIN' < /etc/nginx/templates/nginx.https.conf.template > /etc/nginx/nginx.conf;
        else
          echo '🔄 No certificate yet, starting in HTTP mode' &&
          envsubst '$$DOMAIN' < /etc/nginx/templates/nginx.http.conf.template > /etc/nginx/nginx.conf;
        fi &&
        nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    env_file:
      - .env
    entrypoint: >
      sh -c "
        if [ ! -f /etc/letsencrypt/live/$DOMAIN/fullchain.pem ]; then
          echo '🔄 Issuing new SSL certificate for ${DOMAIN}' &&
          certbot certonly --webroot -w /var/www/certbot -d $DOMAIN \
            --email $EMAIL --agree-tos --no-eff-email --non-interactive;
        else
          echo '✅ Certificate already exists';
        fi &&
        while :; do
          certbot renew --webroot -w /var/www/certbot --quiet;
          sleep 12h;
        done"

volumes:
  certbot-etc:
  certbot-var:
  webroot: