version: "3.8"

services:
  cache-warmer:
    build: .
    container_name: cache-warmer
    restart: always
    env_file:
      - .env

  nginx:
    image: nginx:latest
    container_name: nginx
    restart: always
    ports:
      - "80:80"
      - "443:443"
    env_file:
      - .env
    volumes:
      - ./nginx/nginx.conf.template:/etc/nginx/nginx.conf.template:ro
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    entrypoint: >
      sh -c "envsubst '$$DOMAIN' < /etc/nginx/nginx.conf.template > /etc/nginx/nginx.conf &&
             nginx -g 'daemon off;'"

  certbot:
    image: certbot/certbot
    container_name: certbot
    depends_on:
      - nginx
    volumes:
      - certbot-etc:/etc/letsencrypt
      - certbot-var:/var/lib/letsencrypt
      - webroot:/var/www/certbot
    env_file:
      - .env
    entrypoint: >
      sh -c "trap exit TERM;
             if [ ! -f /etc/letsencrypt/live/${DOMAIN}/fullchain.pem ]; then
               certbot certonly --webroot -w /var/www/certbot \
               -d ${DOMAIN} --email ${EMAIL} --agree-tos --no-eff-email;
             fi;
             while :; do
               certbot renew --webroot -w /var/www/certbot --quiet;
               sleep 12h & wait $${!};
             done"

volumes:
  certbot-etc:
  certbot-var:
  webroot: